package character.feelings;

public enum Feeling implements IFeeling {
	HUNGER, THIRST, EXHAUSTION, SLEEPINESS, PAIN, PLEASURE, STRESS, DISCOMFORT, FEAR, HORROR, DISTRACTION,
	UNWILLINGNESS, ILLNESS, HAPPINESS, DISCONTENT, SATISFACTION, SADNESS, GUILT, ANGER, FRUSTRATION, CONFUSION,
	DEFERENCE, CONTEMPT, SHYNESS, CARE, ATTRACTION, EMBARRASSMENT, AWKWARDNESS, DISGUST, SHAME, SUSPICION, AMUSEMENT,
	UNCERTAINTY, DISAPPOINTMENT, WONDER, STRANGE;

}
