package character.thought;

import java.util.Collection;
import java.util.List;

import character.feelings.IFeeling;
import character.targeting.ITopic;
import character.targeting.IUniqueTopic;
import character.thought.type.IThoughtType;

/**
 * A thought in the mind
 * 
 * @author borah
 *
 */
public interface IThought {

	/**
	 * What type of thought this is
	 * 
	 * @return
	 */
	public IThoughtType thoughtType();

	/**
	 * Who told this thought
	 * 
	 * @return
	 */
	public IUniqueTopic source();

	/**
	 * What feelings this thought generates
	 * 
	 * @return
	 */
	public Collection<IFeeling> feelings();

	/**
	 * the strength of this feeling as generated by the thought
	 * 
	 * @param feeling
	 * @return
	 */
	public int getFeelingStrength(IFeeling feeling);

	/**
	 * A list of all targets fitting
	 * 
	 * @param role
	 * @return
	 */
	public List<ITopic> topicsForThetaRole(ThetaRole role);

	/**
	 * If this type has an argument, return it.
	 * 
	 * @return
	 */
	public IThoughtArgument getArgument();

	/**
	 * If this is a metathought, return the contained tthought
	 * 
	 * @return
	 */
	public IThought thought();

	/**
	 * When this thought was generated
	 * 
	 * @return
	 */
	public long getTimestamp();

	/**
	 * All topics used in this thought
	 * 
	 * @return
	 */
	public Collection<ITopic> allTopics();

}
